name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo GOOGLE_ID=${{ secrets.GOOGLE_ID }} >> .env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env
          echo NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "NEXT_PUBLIC_SITE_URL=${{ secrets.SITE_URL }}" >> .env

      - name: Build Docker Image
        run: docker build -t sumitkrjha/promptgpt:latest .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Image to Docker Hub
        run: docker push sumitkrjha/promptgpt:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull sumitkrjha/promptgpt:latest

      - name: Delete Old Container
        run: docker rm -f promptgpt-container

      - name: Run Docker Container
        run: |
          docker run -d -p 3000:3000 --restart unless-stopped --name promptgpt-container sumitkrjha/promptgpt:latest
